version: "3.9"
services:
  backend:
    extends:
      file: docker-compose_builder.yml
      service: build_backend
    ports:
      - "8080:8080"
    command: java -jar target/inbank.jar

  frontend:
    image: nginx:1.24.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/:/static/
    ports:
      - "80:8080"